"use client";
import Image from "next/image";
import { useState } from "react";
import { Header } from "@/components/Header";
import { Reveal } from "@/components/Reveal";
import { ContactForm } from "@/components/ContactForm";
import { concepts, copy, estateFeatures, model, Lang } from "@/content/translations";

const SectionTitle=({eyebrow,title,lead}:{eyebrow:string;title:string;lead:string})=><Reveal><p className="eyebrow">{eyebrow}</p><h2 className="title serif">{title}</h2><p className="lead">{lead}</p></Reveal>;
const Img=({src,alt}:{src:string;alt:string})=><Image className="img" src={src} alt={alt} width={1600} height={1000}/>;
export default function Home(){const [lang,setLang]=useState<Lang>("en");const c=copy[lang];return <main id="top"><Header lang={lang} setLang={setLang}/><section className="noise" style={{minHeight:"100svh",position:"relative",display:"grid",alignItems:"end",padding:"0 6vw 70px"}}><Image src="/images/hero-altiora.svg" alt="Cinematic remote stone estate with discreet personal eVTOL concept" fill priority style={{objectFit:"cover"}}/><Reveal><div style={{position:"relative",maxWidth:900}}><p className="eyebrow">{c.heroKicker}</p><h1 className="title serif">{c.heroTitle}</h1><p className="lead">{c.heroText}</p><div style={{display:"flex",gap:14,flexWrap:"wrap",marginTop:30}}><a className="btn primary" href="#vision">{c.explore}</a><a className="btn" href="#contact">{c.request}</a></div></div></Reveal><span style={{position:"absolute",bottom:24,right:"6vw",letterSpacing:".22em",fontSize:11}}>SCROLL</span></section>
<section id="vision" className="section"><SectionTitle eyebrow="Manifesto" title="The future does not build new destinations. It unlocks forgotten ones." lead="For more than a century, roads defined real estate value. Personal air mobility may change that logic. Places once considered too remote can become private refuges of exceptional value — provided architecture, energy, access and regulation are treated with equal seriousness."/><div className="grid" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))",marginTop:50}}>{["Own the Unreachable.","What was once unreachable becomes exclusive.","Silence is the new status."].map((x,i)=><Reveal delay={i*.08} key={x}><div className="card" style={{padding:28,minHeight:180}}><h3 className="serif" style={{fontSize:34}}>{x}</h3></div></Reveal>)}</div></section>
<section className="section" style={{background:"#f3efe6",color:"#070706"}}><div className="grid" style={{gridTemplateColumns:"1fr 1fr",alignItems:"center"}}><SectionTitle eyebrow="The Hidden Inventory" title="A fragmented archive of stone, altitude and abandonment." lead="Italy contains a vast and fragmented hidden property inventory: ruderi, casali, abandoned hamlets, shelters, rural stone structures and unused mountain properties. Many occupy positions where new construction would be difficult or impossible to authorise today."/><div className="card"><Img src="/images/hidden-inventory.svg" alt="Hidden inventory of Italian ruins and mountain structures"/></div></div><p className="muted" style={{marginTop:22}}>Working assumption only: references to tens of thousands of abandoned rural and mountain structures require validation during project development.</p></section>
<section id="estates" className="section"><SectionTitle eyebrow="Before / After" title="Conservation first. Intervention second." lead="Original stone is preserved where technically feasible, then paired with large contemporary openings, minimal interiors, solar and storage, water collection, smart home systems and a discreet landing area subject to approvals."/><div className="grid" style={{gridTemplateColumns:"1fr 1fr",marginTop:36}}><div className="card"><Img src="/images/before-ruin.svg" alt="Before: existing stone ruin"/></div><div className="card"><Img src="/images/after-estate.svg" alt="After: restored luxury estate"/></div></div></section>
<section className="section"><SectionTitle eyebrow="The ALTIORA Estate" title="A property, an infrastructure and a private operating system." lead="Each estate is conceived as a complete luxury asset, not a listing: architecture, autonomy, privacy, systems, service and personal flight integration designed as one experience."/><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",marginTop:36}}>{estateFeatures.map((f,i)=><Reveal delay={(i%4)*.04} key={f}><div className="card" style={{padding:22}}><span style={{color:"var(--champagne)"}}>◇</span><h3>{f}</h3></div></Reveal>)}</div></section>
<section className="section" style={{background:"#11100e"}}><div className="grid" style={{gridTemplateColumns:"1fr 1fr",alignItems:"center"}}><div className="card"><Img src="/images/landing-area.svg" alt="Discreet landing infrastructure concept"/></div><SectionTitle eyebrow="Personal Flight" title="Flight-access, without dependence on one aircraft." lead="Jetson ONE is one visible early example of an emerging category. ALTIORA is designed around the broader evolution of personal eVTOL and ultralight aircraft, with every package subject to legal, technical and environmental verification."/></div><p className="muted">Aircraft availability varies by market; regulatory approval, pilot requirements and operating limitations depend on local legislation; landing infrastructure is subject to technical, environmental and planning approvals; no property or aircraft package is offered without prior legal and technical verification.</p></section>
<section className="section"><SectionTitle eyebrow="Flight Changes Value" title="Roads defined real estate for a century. Flight will define what comes next." lead="A remote estate can be perceived differently when transfer time is reduced. Illustrative scenario: 2 hours by mountain road, 18 minutes by personal flight, zero traffic, direct point-to-point access. Times are not guaranteed and depend on aircraft, weather, law and route."/><div className="card" style={{padding:34,marginTop:30}}><div className="grid" style={{gridTemplateColumns:"1fr auto 1fr",alignItems:"center"}}><h3>Mountain road<br/><span className="muted">2 hours illustrative</span></h3><span style={{fontSize:54,color:"var(--champagne)"}}>→</span><h3>Personal flight<br/><span className="muted">18 minutes illustrative</span></h3></div></div></section>
<section className="section" style={{background:"#f3efe6",color:"#070706"}}><div className="grid" style={{gridTemplateColumns:"1fr 1fr",alignItems:"center"}}><SectionTitle eyebrow="Why Italy" title="Landscape density, cultural gravity and rare private locations." lead="Alps, Apennines, Ligurian ridges, rural Tuscany and inland territories create extraordinary diversity near coastlines, cities and heritage. Depopulation has left overlooked structures in places of enduring emotional value."/><div className="card"><Img src="/images/italy-collage.svg" alt="Italian landscape collage"/></div></div></section>
<section id="model" className="section"><SectionTitle eyebrow="Business Model" title="From overlooked asset to flight-access luxury estate." lead="A disciplined sequence turns scarcity into a complete branded ownership experience."/><div style={{marginTop:40}}>{model.map(([a,b],i)=><Reveal key={a}><div style={{display:"grid",gridTemplateColumns:"90px 180px 1fr",gap:20,padding:"24px 0",borderTop:"1px solid var(--line)"}}><span className="eyebrow">0{i+1}</span><h3>{a}</h3><p className="muted">{b}</p></div></Reveal>)}</div></section>
<section id="club" className="section" style={{background:"#11100e"}}><SectionTitle eyebrow="Owners Club" title="More than ownership. A private ecosystem." lead="Aircraft support coordination, estate maintenance, concierge, transfers, chef and hospitality, security, housekeeping, seasonal preparation, experience planning, shared arrival hubs, technical assistance and rental management where applicable."/></section>
<section className="section"><SectionTitle eyebrow="Featured concept estates" title="Three concepts. No addresses. No implied availability." lead="The following estates are architectural and investment concepts, not properties currently offered for sale."/><div className="grid" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))",marginTop:36}}>{concepts.map(e=><article className="card" key={e.title}><Img src={e.image} alt={e.title}/><div style={{padding:22}}><p className="eyebrow">Concept</p><h3 className="serif" style={{fontSize:30}}>{e.title}</h3><p className="muted">{e.desc}</p>{e.meta.map(m=><p key={m}>{m}</p>)}</div></article>)}</div></section>
<section className="section" style={{background:"#f3efe6",color:"#070706"}}><SectionTitle eyebrow="Investment thesis" title="Scarcity-led repositioning, not volume development." lead="The thesis combines distressed or overlooked inventory, high-value repositioning, scarcity-driven luxury, emerging mobility, recurring service revenue, strong brand potential and first-mover positioning — without treating feasibility as automatic."/></section>
<section className="section"><SectionTitle eyebrow="Responsibility and feasibility" title="Vision earns value only when it survives verification." lead="Every development requires urban planning due diligence, title checks, legal access, landscape constraints, environmental compatibility, authorisations, flight safety, meteorology, emergency infrastructure, acoustic impact and technical sustainability."/></section>
<section id="contact" className="section"><div className="grid" style={{gridTemplateColumns:"1fr 1fr",alignItems:"start"}}><SectionTitle eyebrow="Private Access" title="Request a confidential introduction." lead="For estate acquisition, investment, partnerships, architecture and personal flight integration. Submissions are stored only when a contact endpoint is configured."/><ContactForm/></div></section><Footer/></main>}
function Footer(){return <footer className="section" style={{paddingTop:60,borderTop:"1px solid var(--line)"}}><div className="grid" style={{gridTemplateColumns:"1fr 2fr"}}><div><h2 style={{letterSpacing:".24em"}}>ALTIORA ESTATES</h2><p className="serif" style={{fontSize:28}}>Luxury Beyond Roads.</p></div><div className="grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{["Vision","Estates","Owners Club","Partnerships","Contact","Privacy","Legal","Instagram","LinkedIn"].map(x=><a key={x} href={x==="Privacy"?"/privacy":x==="Legal"?"/legal":"#"}>{x}</a>)}</div></div><p className="muted" style={{marginTop:42}}>ALTIORA ESTATES is a conceptual real estate and mobility venture. Images and properties shown may be architectural visualisations. Aircraft availability and operations are subject to applicable regulations, certification, training, weather, local authorisations and technical feasibility.</p></footer>}
